services:
  backend:
    build: ./api
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./app
      args:
        - API_URL=http://localhost:3000/api
    container_name: angular-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
